"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { store } from "./redux/store";
import { Provider } from "react-redux";
import SessionWrapper from "../../components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={inter.className}>
          <h1 className="app-header">Welcome to Redux Toolkit</h1>
          <Provider store={store}>{children}</Provider>
        </body>
      </html>
    </SessionWrapper>
  );
}
